### PR TITLE
Fix correct Android version.

### LINKED ISSUE #24: Broken `RunningAndroidVersion` regex can cause web-compat issue
### Source
https://github.com/wisniewskit/google-search-fixer/blob/108b2781d5f339e6d2b4a242745e48b149db589c/common.js#L1-L7

### Description
The regex `/Android\/[0-9.]+/` does not match Firefox UA and Google Search Fixer always use `Android 6.0`.

### STR
1. Install Google Search Fixer
2. Open `https://www.google.com/search?hl=en&q=tiger`
### Expected result
The 3D result for Bengal tiger is available.
<details>
<summary>Screenshot</summary>

Screenshot1
</details>

### Actual result
The 3D result does not displayed.

<details>
<summary>Screenshot</summary>

Screenshot2
</details>

### Cause
This feature is limited to Android 7 and up.
https://support.google.com/websearch/answer/9817187
> #### Experience 3D & augmented reality in Search
> When you search on Google, you can view some results in 3D and augmented reality (AR).
> ##### What you need
> - To view 3D results: An Android phone with **Android 7 and up**.
> - To interact with 3D results in AR: An Android phone that supports ARCore. [Learn more about which devices support AR](https://developers.google.com/ar/discover/supported-devices).

### PR DESCRIPTION
**Pull request by makotokato**
Fix https://github.com/wisniewskit/google-search-fixer/issues/24. Android version UA in GeckoView is `Android 11`, not `Android/11`.

### CODE REVIEW

File: common.js [hunk 1]
```diff
@@ -1,5 +1,5 @@
 const RunningFirefoxVersion = (navigator.userAgent.match(/Firefox\/([0-9.]+)/) || ["", "58.0"])[1];
-const RunningAndroidVersion = navigator.userAgent.match(/Android\/[0-9.]+/) || "Android 6.0";
+const RunningAndroidVersion = navigator.userAgent.match(/Android\s[0-9.]+/) || "Android 6.0";
```
Comment (Rob--W) [inline common.js:2]:
```suggestion
const RunningAndroidVersion = navigator.userAgent.match(/Android [0-9.]+/) || "Android 6.0";
```

Comment (makotokato) [reply common.js]: Thanks.

**Review by Rob--W — APPROVED** [review]
